# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'AuthDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.0.0'
  pod 'GoogleSignIn'

end
